### ISSUE TITLE
Install script?

### ISSUE THREAD

**Issue by CraigChilds94** [chrisji/ProductiveBash#1]
It'd be great if you wrote a script which copied these to the `/bin` folder and made them executable. :)

**Comment by chrisji** [comment]
Sounds like a good idea, where would you say is best to move them? `/bin`, `usr/local/bin`, `usr/bin`?

**Comment by CraigChilds94** [comment]
I'd do `usr/local/bin`

**Comment by chrisji** [comment]
Agreed! I'll write a simple script for it now, let me know what you think :)

**Comment by CraigChilds94** [comment]
Yeah that looks cool bro!

**Comment by chrisji** [comment]
Cheers for the prompt feedback ;P

**Comment by CraigChilds94** [comment]
Haha sorry I have too many unread notifications on here, I never get a chance to go through them all :'( they pile up toooooo quickly XD

**Comment by CraigChilds94** [comment]
![screen shot 2015-04-01 at 22 27 19](https://cloud.githubusercontent.com/assets/660195/6953012/641d7658-d8be-11e4-9c49-48d66863f032.png)
